services:
  app:
    image: bb-laravel
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: cwf_bb_app
    restart: unless-stopped
    working_dir: /var/www/CWF-BB
    volumes:
      - ./src:/var/www/CWF-BB
    depends_on:
      - db
    networks:
      - cwf_bb_network

  webserver:
    image: nginx
    container_name: cwf_bb_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/CWF-BB
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cwf_bb_network

  db:
    image: mariadb:10.6
    container_name: cwf_bb_mysql
    restart: unless-stopped
    ports:
      - 8000:3306
    environment:
      MYSQL_DATABASE: bulletin_board
      MYSQL_USER: admin_cwf
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - cwf_bb_network

networks:
  cwf_bb_network:
    driver: bridge
